### ISSUE TITLE
What determines how often ALT files are printed?

### ISSUE THREAD

**Issue by r-barnes** [kellykochanski/rescal-snow#10]
Files such as `ALTI00002_t0.log` are demonstrated as being useful for making pretty pictures, but it's unclear what controls the frequency of their generation and whether or not this is tied to the generation of PNG and CSP files. Could you clarify?

**Comment by kellykochanski** [comment]
@defaziogiancarlo can you clarify the work you did on output frequency + controls? I don't remember seeing it in the docs.

Last I worked on it, the "run" script had flags that control output frequency, e.g.:

`./rescal -dpng 20t0 -dcsp 10t0`

but the ALTI frequency could not be explicitly controlled (?).

**Comment by defaziogiancarlo** [comment]
Hi Kelly,

I looked over the Python style comments from last week.

As for ALTI file output frequency controls, there aren't any.
Rescal was set up to output both a .csp and an ALTI file at whatever interval is
set for the .csp files using -dcsp or -dcsphpp.
All I did was add the flag -altionly which disables the .csp output, so you just get the ALTI file.
The frequency is still determined by the -dcsp or -dcsphpp flags.

If you're trying to output .csp and ALTI files at different frequencies, I don't think there's any way to do that without
modifying rescal more. The other way would be to add functionality to datarun.py.

I you want to get just ALTI files, you can modify example_pyrescal.py.

Add the -altionly flag by adding

    'alti only' : True,

to the parameters_run_1 dict

at the bottom, comment out the line

    dr.run_simulation()

and uncomment the line

    dr.run_without_piping()


Then when you run example_pyrescal.py,
the data_runs directory should contain only ALTI files.

The only documentation for this is in rescal itself.
There's a small description about the -altionly flag when you do
./rescal -h

Hope this helps,
If you want I can modify rescal so that you can do something like output a .csp file with
every nth ALTI file.

Gian-Carlo DeFazio
________________________________

**Comment by kellykochanski** [comment]
@defaziogiancarlo  Thank you for clarifying.

**Comment by kellykochanski** [comment]
@r-barnes in light of this comment, I've added a line to the tutorial explaining that `ALTI` files are produced at intervals set by the `-dcsp` flag, and have added a note to the performance docs explaining that large csp file output can be suppressed with `-altionly`.

Closing the issue.
