### ISSUE TITLE
JOSS-Review (@zbeekman): Ack/document MIT licensed CMake stuff & check compatibility

### ISSUE THREAD

**Issue by zbeekman** [kellykochanski/rescal-snow#39]
- The stuff in the `./cmake` subdirectory is all licensed under MIT
  - This should be acknowledged prominently somewhere

I was initially worried that you might have issues redistributing it under/with GPL software but after re-reading the MIT license I think this is OK.

At any rate you might want to confirm with someone who knows more about licensing than I do.

**Comment by kellykochanski** [comment]
@r-barnes Can you comment on this / add the appropriate MIT license notice for cmake?

**Comment by zbeekman** [comment]
The CMake files have MIT licenses in their header comments. I think it probably just needs to be acknowledged in the README? Maybe you can just ignore this; I'm not a lawyer.

**Comment by r-barnes** [comment]
The MIT license requires that the license be noted in "all copies or
substantial portions of the Software" (https://opensource.org/licenses/MIT).
I'm pretty sure that the license's inclusion within the headers of the
files themselves satisfies this requirement.

The MIT license is compatible with GPLv3 and GPLv3 pertains to the work as
a whole but does not otherwise restrict the usage of the portions which are
MIT licensed (https://www.gnu.org/licenses/gpl-faq.html#GPLModuleLicense).

See also:
https://softwareengineering.stackexchange.com/questions/316393/what-to-do-when-using-mit-licensed-code-in-a-gpl-licensed-project
,

So my current stance is that things are good as-is.

**Comment by zbeekman** [comment]
Sounds good! Thanks for educating me!

**Comment by r-barnes** [comment]
Licenses matter: thanks for raising an important and under-appreciated
point :-)
